version: '3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6373:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
