services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: 260800
      POSTGRES_USER: harold
      POSTGRES_DB: resolucion
    volumes:
      - db-data:/var/lib/db-data
    networks:
      - postgres-network

volumes:
  db-data:  
    driver: local

networks:
  postgres-network:
    driver: bridge