version: "1.0"

services:
  mysql:
    image: mysql:8.0.26
    container_name: db-proyecto
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Manuel2024
    - MYSQL_DATABASE:reunion_consejo
  
    ports:
    - 3308:3306
    - 33071:33060
    networks:
    - td2024 Proyecto-final
    
networks:
  td2024 Proyecto-final:
    name: Proyecto-final-td